apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-dev

resources:
    - ../common

patches:
    - path: patches/prometheus-storage.yaml
    - path: patches/grafana-auth.yaml
    - path: patches/prometheus-rbac.yaml
