apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
    - namespace.yaml
    - prometheus-rbac.yaml
    - prometheus.yaml
    - service.yaml
    - servicemonitor.yaml
    - grafana.yaml
    - grafana-service.yaml
    - grafana-dashboard-configmap.yaml
    - grafana-datasource.yaml
    - grafana-dashboard.yaml
