apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
    name: marketplace-prometheus
    labels:
        app.kubernetes.io/name: marketplace-prometheus
spec:
    version: v3.7.3
    replicas: 1
    serviceAccountName: prometheus-k8s
    serviceMonitorSelector:
        matchLabels:
            app.kubernetes.io/name: marketplace-bot-servicemonitor
    podMonitorSelector: {}
    resources:
        requests:
            memory: 256Mi
            cpu: 150m
        limits:
            memory: 512Mi
            cpu: 300m
    retention: 7d
    enableAdminAPI: false
