apiVersion: v1
kind: Service
metadata:
  name: marketplace-prometheus
  labels:
    app.kubernetes.io/name: marketplace-prometheus
spec:
  type: ClusterIP
  selector:
    prometheus: marketplace-prometheus
  ports:
    - name: http
      port: 9090
      targetPort: web
