apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
    - ../common
    - prometheus-rbac.yaml

patches:
    - path: patches/prometheus-storage.yaml
    - path: patches/grafana-auth.yaml
    - path: patches/grafana-storage.yaml
