apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
    name: marketplace-grafana
spec:
    persist: true
    dataStorage:
        type: pvc
        accessModes:
            - ReadWriteOnce
        size: 20Gi
