apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: ozon-bot-prod

labels:
- pairs:
    environment: production
    tier: production

images:
- name: ghcr.io/vshulcz/ozon_price_tracker
  newTag: "sha-c2a2101"

patches:
- path: patches/bot-resources.yaml
- path: patches/postgres-resources.yaml

replicas:
- count: 1
  name: ozon-bot
- count: 1
  name: postgres
