apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: ozon-bot-prod

labels:
  - pairs:
      environment: production
      tier: production

images:
  - name: ghcr.io/vshulcz/ozon_price_tracker
    newTag: latest

patches:
  - path: patches/bot-resources.yaml
  - path: patches/postgres-resources.yaml

replicas:
  - name: ozon-bot
    count: 1
  - name: postgres
    count: 1
