# This is a Kubernetes Secret manifest for storing sensitive information
#
# To create the secret, use the following command:
# kubectl create secret generic bot-secrets -n ozon-bot-prod \
#   --from-literal=BOT_TOKEN='your_token_here' \
#   --from-literal=POSTGRES_PASSWORD='your_password_here'

apiVersion: v1
kind: Secret
metadata:
  name: bot-secrets
type: Opaque
data:
  # Base64 encoded values
  BOT_TOKEN: ""  # echo -n "your_token" | base64
  POSTGRES_PASSWORD: ""  # echo -n "your_password" | base64
