apiVersion: v1
kind: Service
metadata:
  name: marketplace-bot
  labels:
    app: marketplace-bot
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8000"
spec:
  selector:
    app: marketplace-bot
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
      protocol: TCP
